version: "3.8"

services:
  backend:
    image: officenonstop/erp:generic_v15.0
    networks:
      - frappe_network
    depends_on:
      db:
        condition: service_healthy
      redis-cache:
        condition: service_started
      redis-queue:
        condition: service_started
    healthcheck:
      test: ["CMD-SHELL", "bench --version >/dev/null 2>&1 && curl -sf localhost:8000 || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 5
    deploy:
      restart_policy:
        condition: on-failure
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - logs:/home/frappe/frappe-bench/logs
    environment:
      DB_HOST: db
      DB_PORT: "3306"
      MYSQL_ROOT_PASSWORD: admin
      MARIADB_ROOT_PASSWORD: admin

  configurator:
    image: officenonstop/erp:generic_v15.0
    networks:
      - frappe_network
    depends_on:
      backend:
        condition: service_healthy
      db:
        condition: service_healthy
    deploy:
      restart_policy:
        condition: none
    entrypoint:
      - bash
      - -c
    command:
      - >
        echo "🔧 Configuring site settings...";
        ls -1 apps > sites/apps.txt;
        bench set-config -g db_host $$DB_HOST;
        bench set-config -gp db_port $$DB_PORT;
        bench set-config -g redis_cache "redis://$$REDIS_CACHE";
        bench set-config -g redis_queue "redis://$$REDIS_QUEUE";
        bench set-config -g redis_socketio "redis://$$REDIS_QUEUE";
        bench set-config -gp socketio_port $$SOCKETIO_PORT;
        echo "✅ Configurator done.";
    environment:
      DB_HOST: db
      DB_PORT: "3306"
      REDIS_CACHE: redis-cache:6379
      REDIS_QUEUE: redis-queue:6379
      SOCKETIO_PORT: "9000"
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - logs:/home/frappe/frappe-bench/logs

  create-site:
    image: officenonstop/erp:generic_v15.0
    networks:
      - frappe_network
    depends_on:
      backend:
        condition: service_healthy
      db:
        condition: service_healthy
    deploy:
      restart_policy:
        condition: none
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - logs:/home/frappe/frappe-bench/logs
    entrypoint:
      - bash
      - -c
    command:
      - >
        echo "🚀 Starting site creation...";
        wait-for-it -t 120 db:3306;
        wait-for-it -t 120 redis-cache:6379;
        wait-for-it -t 120 redis-queue:6379;

        echo "🔍 Checking app folders before creating site...";
        for app in erpnext hrms insights payments india_compliance netmanthan_themes; do
          if [ ! -d "apps/$app" ]; then
            echo "❌ Missing app folder: $app"; exit 1;
          fi
        done;

        echo "✅ All app folders found.";

        export start=$(date +%s);
        until [[ -n `grep -hs ^ sites/common_site_config.json | jq -r ".db_host // empty"` ]] && \
              [[ -n `grep -hs ^ sites/common_site_config.json | jq -r ".redis_cache // empty"` ]] && \
              [[ -n `grep -hs ^ sites/common_site_config.json | jq -r ".redis_queue // empty"` ]];
        do
          echo "Waiting for sites/common_site_config.json to be created...";
          sleep 5;
          if (( $(date +%s)-start > 120 )); then
            echo "❌ Could not find sites/common_site_config.json with required keys."; exit 1;
          fi
        done;

        echo "✅ sites/common_site_config.json found. Creating site...";
        bench new-site --mariadb-user-host-login-scope='%' \
                       --admin-password=admin \
                       --db-root-username=root \
                       --db-root-password=admin \
                       --install-app erpnext \
                       --set-default frontend || exit 1;

        echo "🔍 Installing additional apps...";
        for app in hrms payments insights india_compliance netmanthan_themes; do
          if ! bench --site frontend list-apps | grep -q "$app"; then
            echo "⚙️ Installing $app..."; bench --site frontend install-app "$app" || exit 1;
          else
            echo "✔️ $app already installed, skipping.";
          fi
        done;

        echo "✅ Site creation and app installation complete.";

  db:
    image: mariadb:10.7
    networks:
      - frappe_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "--password=admin"]
      interval: 10s
      timeout: 5s
      retries: 10
    deploy:
      restart_policy:
        condition: on-failure
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
      - --skip-innodb-read-only-compressed
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MARIADB_ROOT_PASSWORD: admin
    volumes:
      - db-data:/var/lib/mysql

  frontend:
    image: officenonstop/erp:generic_v15.0
    networks:
      - frappe_network
    depends_on:
      backend:
        condition: service_healthy
      websocket:
        condition: service_started
    deploy:
      restart_policy:
        condition: on-failure
    command:
      - nginx-entrypoint.sh
    environment:
      BACKEND: backend:8000
      FRAPPE_SITE_NAME_HEADER: frontend
      SOCKETIO: websocket:9000
      UPSTREAM_REAL_IP_ADDRESS: 127.0.0.1
      UPSTREAM_REAL_IP_HEADER: X-Forwarded-For
      UPSTREAM_REAL_IP_RECURSIVE: "off"
      PROXY_READ_TIMEOUT: 120
      CLIENT_MAX_BODY_SIZE: 50m
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - logs:/home/frappe/frappe-bench/logs
    ports:
      - "8080:8080"

  queue-long:
    image: officenonstop/erp:generic_v15.0
    networks:
      - frappe_network
    depends_on:
      backend:
        condition: service_healthy
    deploy:
      restart_policy:
        condition: on-failure
    command:
      - bench
      - worker
      - --queue
      - long,default,short
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - logs:/home/frappe/frappe-bench/logs

  queue-short:
    image: officenonstop/erp:generic_v15.0
    networks:
      - frappe_network
    depends_on:
      backend:
        condition: service_healthy
    deploy:
      restart_policy:
        condition: on-failure
    command:
      - bench
      - worker
      - --queue
      - short,default
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - logs:/home/frappe/frappe-bench/logs

  redis-queue:
    image: redis:6.2-alpine
    networks:
      - frappe_network
    deploy:
      restart_policy:
        condition: on-failure
    volumes:
      - redis-queue-data:/data

  redis-cache:
    image: redis:6.2-alpine
    networks:
      - frappe_network
    deploy:
      restart_policy:
        condition: on-failure

  scheduler:
    image: officenonstop/erp:generic_v15.0
    networks:
      - frappe_network
    depends_on:
      backend:
        condition: service_healthy
    deploy:
      restart_policy:
        condition: on-failure
    command:
      - bench
      - schedule
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - logs:/home/frappe/frappe-bench/logs

  websocket:
    image: officenonstop/erp:generic_v15.0
    networks:
      - frappe_network
    depends_on:
      backend:
        condition: service_healthy
    deploy:
      restart_policy:
        condition: on-failure
    command:
      - node
      - /home/frappe/frappe-bench/apps/frappe/socketio.js
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - logs:/home/frappe/frappe-bench/logs

volumes:
  db-data:
  redis-queue-data:
  sites:
  logs:

networks:
  frappe_network:
    driver: bridge
