version: "3.8"

services:
  backend:
    image: officenonstop/erp:generic_v15.0
    networks:
      - frappe_network
    depends_on:
      db:
        condition: service_healthy
      redis-cache:
        condition: service_started
      redis-queue:
        condition: service_started
    healthcheck:
      test: ["CMD-SHELL", "bench --version >/dev/null 2>&1 && curl -sf localhost:8000 || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 5
    deploy:
      restart_policy:
        condition: on-failure
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - logs:/home/frappe/frappe-bench/logs
    environment:
      DB_HOST: db
      DB_PORT: "3306"
      MYSQL_ROOT_PASSWORD: admin
      MARIADB_ROOT_PASSWORD: admin

  configurator:
    image: officenonstop/erp:generic_v15.0
    networks:
      - frappe_network
    depends_on:
      backend:
        condition: service_healthy
      db:
        condition: service_healthy
    deploy:
      restart_policy:
